config/routes.rb
Rails.application.routes.draw do

  root :to =>'home#index'
  #cemetory controller routes
  get '/new',   to: 'cemetories#new'
  post '/create',   to: 'cemetories#create'
  get '/edit',   to: 'cemetories#edit'
  get '/list',   to: 'cemetories#cemetorylist'
  get '/destroy',   to: 'cemetories#destroy'

  get '/indexsearch', to: 'cemetories#index'

  get '/showresult', to: 'cemetories#show'
  # get '/livesearch', to: 'cemetories#livesearch'

  get "/livesearch" => 'cemetories#livesearch'
  #home routes default

  get '/home',   to: 'home#index'
  post '/home',   to: 'home#index'

  #staticpages routes
  get '/contact',   to: 'staticpages#contact'

  get '/home1',      to: 'staticpages#home'

  get '/help',      to: 'staticpages#help'

  get '/about',     to: 'staticpages#about'

  #resource for thedevise
  devise_for :users,controllers:{registrations: 'users/registrations',omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  #resource of ransack searching
  resources :cemetories do
    collection { post :search, to: 'cemetories#index' }
  end

end

app/models/cemetory.rb
class Cemetory < ApplicationRecord
  belongs_to :user

  validates :fullname, presence: true,length: { minimum: 3, :maximum => 20}
  validates :dob,:dod, presence: true
end

app/controllers/cemetories_controller.rb
class CemetoriesController < ApplicationController
  #searching using ransack
  def index
    # for button search
  end

  #for live search with ajax
  def livesearch
    search=params[:data]
       if search.blank?
         cemetories=Cemetory.all
         gmap cemetories
        else
          cemetory=Cemetory.where('lower(fullname) LIKE ?', "%#{search}%")
          gmap cemetory
        end
        respond_to do |format|
          format.html
          format.js
        end
   end

    #method for deadbody info
    def new
      @cemetory=Cemetory.new
    end

    def create
      @cemetory=Cemetory.new(cemetory_params)
      if @cemetory.save
            flash[:success] = "Cemetory details successfully saved."
            redirect_to list_path
      else
          flash[:danger] = "Cemetory details failed."
          render 'new'
      end
    end

    #list of data
    def cemetorylist
      @cemetories=Cemetory.all
    end

#destroy the cemetery detail from list
  def destroy
    cemetory=Cemetory.find(params[:id])
    if cemetory.destroy
      flash[:success] = "Cemetory record deleted.."
      redirect_to list_path
    else
      flash[:danger] = "Cemetory record not found.."
      redirect_to list_path
    end
  end

  private
  def cemetory_params
    params.require(:cemetory).permit(:fullname, :dob, :cemetoryaddress, :gender, :user_id, :relation, :dod, :lang, :lat)
  end

  def gmap record
      @hash = Gmaps4rails.build_markers(record) do |cemetory, marker|
          marker.lat cemetory.lat
          marker.lng cemetory.lang
          marker.infowindow cemetory.fullname
      end
    end


end

app/helpers/cemetory_helper.rb
module CemetoryHelper
end

app/views/cemetories/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:user_id] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
    <%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</div>

app/views/cemetories/_search.html.erb
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

  markers = handler.addMarkers(<%=raw @hash.to_json %>);

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>
<br/>

app/views/cemetories/cemetorylist.html.erb
<% if @cemetories.blank? %>
  <p>There are not any cemetory reference currently in the system.</p>
<% else %>
<br/>
<p>These are the current cemetory records in our system</p>
<br/>

<div class="container">
<table border="1" class="table">
  <th>Member name</th>
  <th>Dob</th>
  <th>Dod</th>
  <th>Cemetory address</th>
  <th>Relation</th>
  <th>Gender</th>
  <th>Age</th>
  <th>Delete</th>

  <% @cemetories.each do |c| %>
    <tr>
        <td>
          <%= c.fullname%>
        </td>
        <td>
          <%= c.dob%>
        </td>
        <td>
          <%= c.dod%>
        </td>
        <td>
          <%= c.cemetoryaddress%>
        </td>
        <td>
          <%= c.relation%>
        </td>
        <td>
          <% if c.gender == true %>
          <h6>Female</h6>
          <% else %>
          <h6>Male</h6>
          <% end %>
        </td>
        <td>
          <% now = Time.now.utc.to_date %>
          <%= c.dod.year - c.dob.year %>
        </td>
        <td>
          <%= link_to 'Delete', destroy_path(:id => c.id),data: { confirm: "Are you sure?" } -%>
        </td>
    </tr>
  <% end %>
</table>

</div>

<% end %>
<div class="space"></div>
<p><%= link_to "Book new Cemetory", new_path %></p>
<div class="space"></div>

app/views/cemetories/edit.html.erb
<p>select any one option.....</p>
<div id="f1"><input type="radio" name="people" value="one" />Form for you!<br/></div>
<div id="formforyou">

  <h2>cemetoryform for you</h2>
  <%= form_for @cemetoryData, :url =>{:action => "update",:id=>@cemetoryData} do |f| %>

    <p>Full Name:   <%= f.text_field :fullname, autofocus: true %></p>
    <p>Date of Birth:<%= f.text_field :dob, :class=>'datepicker' %></p>
    <p>Date of death:<%= f.text_field :dod, :class=>'datepicker' %></p>
    <p>Relation:   <%= f.text_field :relation, autofocus: true %></p>
    <p>Cemetory Address:  <%= f.text_area :cemetoryaddress %>
      You can be provide any of the cemetory address which you want to select in surat only.</p>
    <p>
        <%= f.label :gender_male, 'Male' %><%= f.radio_button :gender, 'false', :checked => true %>
        <%= f.label :gender_female, 'Female' %><%= f.radio_button :gender, 'true' %>
    </p>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.submit "Save changes" %>
      <% end %>
  </div>

<script>

  $(document).ready(function(){
    $("#formforyou").hide();
    $("#formforfamily").hide();

    $("input:radio[name='people']").change(function(){

      if(this.value == 'one' && this.checked){
        $("#formforyou").show();
        $("#formforfamily").hide();
        $("#f2").hide();
      }else{
        $("#f1").hide();
        $("#formforyou").hide();
        $("#formforfamily").show();
      }

    });

  });
</script>
<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();

  });
</script>

app/views/cemetories/livesearch.html.erb
<br/>
  <%= text_field_tag :search, params[:search],:placeholder=>'Search cemetery info here....',:class=>'livemap' %>
<span class="fa fa-search"></span>
<br/><br/>
<div id="map" class="map1"></div>

<div id="searchlist"><%= render 'search'%></div>

<script>
  $(document).ready(function(){
    $('#search').keyup(function(){
      var text=this.value;
      //alert("Data: " + text );

      $.get("livesearch", function(data){
        //alert("Data: " + text );
        if(text)
        {
          $.ajax({
            type: "get",
            url: "/livesearch",
            dataType: 'script',
            data: {"data" : text.toLowerCase()}
          });
        }
      });
    });
  });
</script>

app/views/cemetories/livesearch.js.erb
// $("#search").html("<%= escape_javascript(render("search")) %>");
 $('#searchlist').html('<%= escape_javascript(render("search")) %>');

app/views/cemetories/new.erb
<div class="space"></div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Cemetery Form</h1>
      <%= form_for @cemetory, :url =>{:action => "create"}  do |f| %>

        <div class="form-group">
          <%= f.text_field :fullname, :class=>"form-control", :id=>"exampleInputEmail1",:placeholder=>"Enter Fullname"%>
        </div>

        <div class="form-group">
           <%= f.text_field :relation, :class=>"form-control", :id=>"exampleInputPassword1", :placeholder=>"Enter Relation"%>
        </div>

        <label>Select map address</label>
        <div id="map_canvas" class="map2"></div>

        <div class="form-group">
            <%= f.text_area :cemetoryaddress, :class=>"form-control" %>
        </div>

        <div class="form-group">
          <label>Select date of birth :</label>
          <%= f.date_select :dob,:start_year=>Date.today.year - 35, :end_year=>Date.today.year,:class=>"form-control", :placeholder=>"Enter Date Of Birth" %>
        </div>

        <div class="form-group">
          <label>Select date of death:</label>
          <%= f.date_select :dod,:start_year=>Date.today.year - 5,:end_year=>Date.today.year,:class=>"form-control", :placeholder=>"Enter Date Of Death" %>
        </div>

        <div class="form-group">
          <%= f.label :gender_male, 'Male' %><%= f.radio_button :gender, 'false', :checked => true %>
          <%= f.label :gender_female, 'Female' %><%= f.radio_button :gender, 'true' %>
        </div>

        <br/><br/>

        <%= f.hidden_field :lang %>
        <%= f.hidden_field :lat %>
        <%= f.hidden_field :user_id, :value => current_user.id %>

        <%= f.submit "Save changes",:class=>"btn btn-primary my-btn dark" %>

      <% end %>

    </div>
</div>

<script>

  var geocoder;
  var map;
  var markersArray = [];

  function placeMarkerAndPanTo(latLng, map) {
    var position = latLng;
    console.log(position);
    while (markersArray.length) {
      markersArray.pop().setMap(null);
    }
    var marker = new google.maps.Marker({
      draggable: true,
      position: latLng,
      map: map,
      title: "Select Your Location!"

    });
    map.panTo(latLng);

    markersArray.push(marker);

    google.maps.event.addListener(marker, 'dragend', function(event) {
      var position = event.latLng;
      console.log(position);
    });
  }

  function initialize() {
    var map = new google.maps.Map(
      document.getElementById("map_canvas"), {
        center: new google.maps.LatLng({lat: 21.17277096919513,lng: 72.8353214263916}),
        zoom: 10,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });

      map.addListener('click', function(e) {

        $("#cemetory_lat").val(e.latLng.lat()); //val assign in
        $("#cemetory_lang").val(e.latLng.lng());
        var geocoder = new google.maps.Geocoder;
        geocodeLatLng(geocoder,e.latLng);
        placeMarkerAndPanTo(e.latLng, map);
      });

      function geocodeLatLng(geocoder,addr)
      {
        var latlng = addr;
        geocoder.geocode({'location': latlng}, function(results, status)
        {
          if (status === 'OK')
          {
            if (results[0])
            {
              $("#cemetory_cemetoryaddress").val(results[0].formatted_address);

            }
            else
            {
              alert('No results found');
            }
          }
          else
          {
            alert('Geocoder failed due to: ' + status);
          }
        });
      }
    }
  google.maps.event.addDomListener(window, "load", initialize);
  //google.setOnLoadCallback(initialize);
  </script>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWtPc7P3WE-qisP-f-tSiGZJO__iD6Pw8&callback=initialize">
  </script>
  <!-- <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker();

    });
  </script> -->