config/routes.rb
Rails.application.routes.draw do

  root :to =>'home#index'
  #cemetory controller routes
  get '/new',   to: 'cemetories#new'
  post '/create',   to: 'cemetories#create'
  get '/edit',   to: 'cemetories#edit'
  get '/list',   to: 'cemetories#cemetorylist'
  get '/destroy',   to: 'cemetories#destroy'

  get '/indexsearch', to: 'cemetories#index'

  get '/showresult', to: 'cemetories#show'
  # get '/livesearch', to: 'cemetories#livesearch'

  get "/livesearch" => 'cemetories#livesearch'
  #home routes default

  get '/home',   to: 'home#index'
  post '/home',   to: 'home#index'

  #staticpages routes
  get '/contact',   to: 'staticpages#contact'

  get '/home1',      to: 'staticpages#home'

  get '/help',      to: 'staticpages#help'

  get '/about',     to: 'staticpages#about'

  #resource for thedevise
  devise_for :users,controllers:{registrations: 'users/registrations',omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  #resource of ransack searching
  resources :cemetories do
    collection { post :search, to: 'cemetories#index' }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @search = Cemetory.search(params[:q])
    result = @search.result
    @hash = Gmaps4rails.build_markers(result) do |r, marker|
      marker.lat r.lat
      marker.lng r.lang
      marker.infowindow r.fullname
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= search_form_for @search, url: home_path,method: :post do |f| %>
<div class="field">
  <%= f.text_field :fullname_cont,:placeholder=>'Search member info here....',:class=>'indexmap'%>
  <%= f.submit "Search"%>
</div>
<% end %>
<br/>

<div>
    <div id="map" class="map1"></div>
</div>

<br/><br/>

<script>
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

      markers = handler.addMarkers(<%=raw @hash.to_json %>);

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
</script>