config/routes.rb
Rails.application.routes.draw do

  root :to =>'home#index'
  #cemetory controller routes
  get '/new',   to: 'cemetories#new'
  post '/create',   to: 'cemetories#create'
  get '/edit',   to: 'cemetories#edit'
  get '/list',   to: 'cemetories#cemetorylist'
  get '/destroy',   to: 'cemetories#destroy'

  get '/indexsearch', to: 'cemetories#index'

  get '/showresult', to: 'cemetories#show'
  # get '/livesearch', to: 'cemetories#livesearch'

  get "/livesearch" => 'cemetories#livesearch'
  #home routes default

  get '/home',   to: 'home#index'
  post '/home',   to: 'home#index'

  #staticpages routes
  get '/contact',   to: 'staticpages#contact'

  get '/home1',      to: 'staticpages#home'

  get '/help',      to: 'staticpages#help'

  get '/about',     to: 'staticpages#about'

  #resource for thedevise
  devise_for :users,controllers:{registrations: 'users/registrations',omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  #resource of ransack searching
  resources :cemetories do
    collection { post :search, to: 'cemetories#index' }
  end

end

app/views/layouts/_footer.html.erb
<nav id="tf-footer">
		<div class="container">
				 <div class="pull-left">
						<p>2017 © CemeteryApp. All Rights Reserved. Designed and Coded by <span>Asmita kalena</span></p>
				</div>
				<div class="pull-right">
						<ul class="social-media list-inline">
						</ul>
				</div>
		</div>
</nav>

app/views/layouts/_header.html.erb
<div id="tf-home">
  <div class="overlay">
    <div id="sticky-anchor"></div>
     <nav id="tf-menu" class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <%= link_to "Register Cemetery", root_path, :class=>"navbar-brand logo"%>
          </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to root_path do %><i class="fa fa-home"></i><% end -%>
              </li>

              <li>
                <%= link_to 'Live search', livesearch_path%>
              </li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <% if user_signed_in? %>

                <li><%= link_to 'Cemetory Form', new_path %></li>
                <li><%= link_to 'Cemetory List', list_path%></li>

                <li class="dropdown">
                    <%= link_to 'Settings',:class=>"dropbtn" %>
                    <div class="dropdown-content">
                      <%= link_to 'Edit profile', edit_user_registration_path %>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                    </div>
                </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <div class="content">
        <% if user_signed_in? %>
        <div class="logininfo">Logged in as <strong><%= current_user.email %></strong>.</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Cemetery App">
  <meta name="author" content="Asmita kalena">
  <title>CementryApp</title>
  <%= csrf_meta_tags %>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWtPc7P3WE-qisP-f-tSiGZJO__iD6Pw8&callback=initialize">
  </script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>
<body>
      <%= render 'layouts/header' %>
      <div class="container">
          <br/>
          <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
          <% end %>

          <%= yield %>
        <!-- <%= debug(params) if Rails.env.development? %> -->
      </div>
      <br/>
     <%= render 'layouts/footer' %>
</body>
</html>